### ISSUE TITLE
Tap API dose not match the expected effect in the mode of LANDSCAPE

### ISSUE THREAD

**Issue by dawangraoming** [facebook/WebDriverAgent#836] opened 2018-01-08 13:02 UTC
## Environment 环境
Machine: iPhone 7
OS Version: 11.2.1
Xcode Version: 9.2

设备: iPhone 7
OS 版本: 11.2.1
Xcode 版本: 9.2

## Bug description 描述
I'm trying to use Notes App to make the details of bug more specific. When the iPhone is under the situation of rotation and using `tap` api meanwhile, the position of clicking will fail to live up to the result of expectation. Just like what I will mention in the picture following. Everytime using shell to execute the shell which third X is 400, the position of clicking will be on left and the position of Y will also be in deviation simultaneously.

我尝试使用备忘录应用来还原Bug详情，当iPhone处于旋转的状态下时使用`tap`API，点击的位置将与预期结果不一致！如下图，我使用下方的Shell，当执行第三条X为400的Shell时，点击位置跑到了左侧，并且Y的位置也出现了偏移

![img_6683](https://user-images.githubusercontent.com/7522275/34670458-552a2ddc-f4b1-11e7-8b86-ac0bb760ed45.jpg)

## Shell

```
curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8100/session/456A51D5-F3D2-420A-9236-C8103A818412/wda/tap/0 -d "{\"x\":\"200\",\"y\":\"200\"}"
curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8100/session/456A51D5-F3D2-420A-9236-C8103A818412/wda/tap/0 -d "{\"x\":\"300\",\"y\":\"200\"}"
curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8100/session/456A51D5-F3D2-420A-9236-C8103A818412/wda/tap/0 -d "{\"x\":\"400\",\"y\":\"200\"}"
```

**Comment by psyche08** [comment] 2018-01-08 13:10
same issue,  it looks like the x can not greater than height

**Comment by dawangraoming** [comment] 2018-01-09 02:23
@psyche08 I guess what caused this problem is that X is greater than the width of iPhone

**Comment by Arrow-Li** [comment] 2018-01-09 10:57
I found a temporary solution.

> **tap(x/2,y/2)**

**Comment by DeviLeo** [comment] 2018-02-24 06:59
Here is the temporary solution.
Find the file, __WebDriverAgent/WebDriverAgentLib/Commands/FBElementCommands.m__ .    
Locate the method, __+ (id<FBResponsePayload>)handleTap:(FBRouteRequest *)request__ .  
Fix the codes:  
``` Objective-C
+ (id<FBResponsePayload>)handleTap:(FBRouteRequest *)request
{
  FBElementCache *elementCache = request.session.elementCache;
  CGPoint tapPoint = CGPointMake((CGFloat)[request.arguments[@"x"] doubleValue], (CGFloat)[request.arguments[@"y"] doubleValue]);
  XCUIElement *element = [elementCache elementForUUID:request.parameters[@"uuid"]];
  if (nil == element) {
    //>> Fix Start
    NSArray<XCUIElement *> *allElements = request.session.application.windows.allElementsBoundByIndex;
    XCUIElement *window = nil;
    for (XCUIElement *e in allElements) {
      if (e.elementType == XCUIElementTypeWindow) {
        window = e;
        break;
      }
    }
    XCUIElement *e = window ?: request.session.application;
    XCUICoordinate *tapCoordinate = [self.class gestureCoordinateWithCoordinate:tapPoint application:(id)e shouldApplyOrientationWorkaround:isSDKVersionLessThan(@"11.0")];
    //<< Fix End
    [tapCoordinate tap];
  } else {
    NSError *error;
    if (![element fb_tapCoordinate:tapPoint error:&error]) {
      return FBResponseWithError(error);
    }
  }
  return FBResponseWithOK();
}
```

Pass the window element object instead of the FBApplication object to the __gestureCoordinateWithCoordinate:application:shouldApplyOrientationWorkaround:__ method.  

Tested on iPhone 7 (iOS 11.1.1)

**Comment by marekcirkos** [comment] 2018-02-28 17:58
Looks like duplicate of https://github.com/facebook/WebDriverAgent/issues/856 ? Can you provide a PR for this fix?

**Closed** 2018-02-28 18:19 UTC
