### ISSUE TITLE
How to  use "[[FBRoute POST:@"/url"] respondWithTarget:self action:@selector(handleOpenURL:)]"

### ISSUE THREAD

**Issue by YoungL92** [facebook/WebDriverAgent#691] opened 2017-08-23 12:18 UTC
In WebDriverAgentLib/Conmands/FBSessionCommands.m

[[FBRoute POST:@"/url"] respondWithTarget:self action:@selector(handleOpenURL:)]

How to use this?

**Comment by marekcirkos** [comment] 2017-10-20 14:22
Duplicate of https://github.com/facebook/WebDriverAgent/issues/686

**Closed by marekcirkos** 2017-10-20 14:22 UTC
