### ISSUE TITLE
locate element by predicate string, wda crashed

### ISSUE THREAD

**Issue by dengwei729** [facebook/WebDriverAgent#346] opened 2016-11-02 02:15 UTC
Try to locate element by predicate string , wda crashed

```
(lldb) po query
    t =    26.18s     Use cached accessibility hierarchy for local.pid.57
    t =    26.23s     Find: Descendants matching type Any
    t =    26.27s     Find: Elements matching predicate 'name CONTAINS "没有找到相关城市"'
0x000000017008e010

    t =    36.43s         Get all elements bound by index for: Elements matching predicate 'name CONTAINS "没有找到相关城市"'
    t =    36.67s             Snapshot accessibility hierarchy for local.pid.57
    t =    36.75s             Find: Descendants matching type Any
    t =    36.76s             Find: Elements matching predicate 'name CONTAINS "没有找到相关城市"'
2016-11-02 10:08:09.639247 XCTRunner[274:9050] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<XCElementSnapshot 0x174175240> valueForUndefinedKey:]: this class is not key value coding-compliant for the key name.'
*** First throw call stack:
(0x1816741c0 0x1800ac55c 0x181673e88 0x182115500 0x18205c3a8 0x18209e620 0x18209e23c 0x18209d220 0x18209d018 0x100224438 0x100225a58 0x1001f5afc 0x10022595c 0x1002253dc 0x1001f5afc 0x10022535c 0x106d01514 0x106d0112c 0x106d00c10 0x106cffe60 0x106d0d954 0x106cef310 0x1804fd200 0x1804fd1c0 0x180501d6c 0x181621f2c 0x18161fb18 0x18154e048 0x18205cb1c 0x1820b12a0 0x106cffaa8 0x106ccae20 0x18167a160 0x18156dc3c 0x1001f234c 0x100226e9c 0x1001f21b0 0x1001f2884 0x1001efd00 0x1001efd00 0x1001efd00 0x1001dbc74 0x1001fc504 0x1001dbb0c 0x1001dc890 0x100228368 0x181622160 0x18162195c 0x18161f7b0 0x18154e048 0x182fd1198 0x187528628 0x187523360 0x1000f83d4 0x1805305b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
 ```

**Comment by marekcirkos** [comment] 2016-11-02 10:31
That is not good. Can you paste request you are making?

**Comment by mykola-mokhnach** [comment] 2016-11-02 18:30
@dengwei729 can you try to replace _name_ with _wdName_ and/or _title_ in your query?

@marekcirkos Can you please advice on predicate locators documentation in https://github.com/appium/appium/issues/6777#issuecomment-257951851 ?

**Comment by marekcirkos** [comment] 2016-11-04 10:05
I don't like the fact we have predicate support, because that people need to know internal implementation. I think we either should kill it (it is unsafe) or validate and translate predicates.

**Comment by marekcirkos** [comment] 2016-11-08 09:42
Duplicate of https://github.com/facebook/WebDriverAgent/issues/352

**Closed by marekcirkos** 2016-11-08 09:42 UTC
