### ISSUE TITLE
Webdriver server get hanged on executing commands on IOS 11 with Appium

### ISSUE THREAD

**Issue by swachhab** [facebook/WebDriverAgent#706] opened 2017-09-06 13:08 UTC
Need help!
I am trying executing automation on IOS 11(Beta 9), all commands are executing fine but its pretty slow. It is taking around 40 seconds to execute next command without any sleep.
Moreover there are no exception or message in logs for such late execution.
Environment Details:
IOS 11 Beta 9
Appium 1.6.5 and Appium 1.6.6 Beta
Xcode 9 Beta 6

If anybody tried execution on IOS 11, so please help me out.

**Comment by marekcirkos** [comment] 2017-10-23 10:37
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by marekcirkos** 2017-10-23 10:37 UTC
