### ISSUE TITLE
WDA doesn't work on iOS 10.1

### ISSUE THREAD

**Issue by Royshcn** [facebook/WebDriverAgent#354] opened 2016-11-07 06:42 UTC
My test device is an iPhone 7 ion 10.1. I used xcode to run test  and got following error,

XCTRunner[1076:264505] [User Defaults] Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x1700e8300> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only

any ideas about this?

**Comment by marekcirkos** [comment] 2016-11-07 10:34
Can you try commenting `[FBConfiguration shouldShowFakeCollectionViewCells:YES]` in `UITestingUITests.m`?

**Comment by Royshcn** [comment] 2016-11-07 12:08
I  commented it.  The error is gone but I still can't access the device via safari.

**Comment by marekcirkos** [comment] 2016-11-07 14:50
Is your phone and mac on the same wifi?

**Comment by marekcirkos** [comment] 2016-11-08 09:39
Duplicate of https://github.com/facebook/WebDriverAgent/issues/288

**Closed by marekcirkos** 2016-11-08 09:39 UTC
