### ISSUE TITLE
Test failing when try to clear a text field

### ISSUE THREAD

**Issue by FranMartinRomero** [facebook/WebDriverAgent#606] opened 2017-06-02 14:21 UTC
We are having an issue when we try to clear a textfield like this 
`emailElement.clear();`

The test is failing with the message 

> Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to make any progress while clearing text"

We are using the latest version of WebDriverAgent, Appium 1.6.5, Xcode 8.3.2, Simulator iPhone 6S iOS 10.0

Any clue about this issue?

**Comment by majdy86** [comment] 2017-06-13 12:57
Iam facing same issue.

AppiumLogs :[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Error Domain=com.facebook.WebDriverAgent Code=1 \\\"Failed to make any progress while clearing text\\\" UserInfo={NSLocalizedDescription=Failed to make any progress while clearing text}

**Comment by cosminstirbu** [comment] 2017-06-16 14:18
Facing the same issue:

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to make any progress while clearing text" UserInfo={NSLocalizedDescription=Failed to make any progress while clearing text} (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 1.76 seconds
      Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
      System info: host: 'oasdasd', ip: 'asdasd', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_91'
      Driver info: io.appium.java_client.ios.IOSDriver
      Capabilities [{app=/MyApp.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone 5s, platform=MAC, newCommandTimeout=300, platformVersion=9.3, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=419974E6-A221-4AAA-AF9F-5289DFF5D143}]
      Session ID: 08eaa650-21e8-48a2-b1a7-c732a5849b0d
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
      	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
      	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
      	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
      	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
      	at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:33)
      	at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
      	at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)
      	at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:140)
      	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:498)
      	at io.appium.java_client.pagefactory.ElementInterceptor.getObject(ElementInterceptor.java:39)
      	at io.appium.java_client.pagefactory.interceptors.InterceptorOfASingleElement.intercept(InterceptorOfASingleElement.java:58)
      	at io.appium.java_client.ios.IOSElement$$EnhancerByCGLIB$$184e91dc.clear(<generated>)
```
It is occurring intermittently however.

**Comment by marekcirkos** [comment] 2017-07-14 08:59
Could you provide a video?

**Comment by larryricker** [comment] 2017-07-22 02:46
@marekcirkos I am experiencing this issue clearing a text area field.  More specifically, it is a UITextView field named questionTextField.  The source for the automated test is at https://github.com/larryricker/ProjectOrganizerAppium.  The video of the test and my attempts to mitigate it are at https://youtu.be/VDqJ8YiEHxU

**Comment by VaishinaviRajaraman** [comment] 2017-08-08 04:35
Facing the above. @larryricker @cosminstirbu @majdy86 @FranMartinRomero is there anything to work around this issue until it's fixed?

**Comment by bgpros** [comment] 2017-08-28 15:21
Facing same issue, Can't clear a textfield, any solutions or workarounds?

**Comment by VaishinaviRajaraman** [comment] 2017-08-28 23:25
@bgpros I have downgraded selenium version to 3.3.1 and that has helped. You can give that a go.

**Comment by codeskyblue** [comment] 2017-08-29 01:27
It is also failed to clear text, the TextField has already content and cursor is on the left.

**Comment by marekcirkos** [comment] 2017-10-23 09:14
Duplicate of https://github.com/facebook/WebDriverAgent/issues/603

**Closed by marekcirkos** 2017-10-23 09:14 UTC

**Comment by haseebzagir** [comment] 2018-07-20 12:07
Toggle the software keyboard under Hardware > Keyboard > Software Keyboard or Cmd + K and see your textfields working like a charm.
