### ISSUE TITLE
Session-less screenshot not working

### ISSUE THREAD

**Issue by billios1111** [facebook/WebDriverAgent#868] opened 2018-02-15 17:30 UTC
Might be related to #845. The most recent comment in Appium Issue #9549 mentions something about XCode 9 compatibility issues with iOS 10 which might be what I am experiencing here now.

My environment:
- macOS 10.13.3
- iOS 10.1.1
- Xcode 9.0
- a real iPhone 5s

I am attempting to grab screenshots without a session using the /screenshot endpoint. Grabbing screenshots in a session (/session/<id>/screenshot) works perfectly fine. However session-less only works on occasion, and fails most of the time. The response I am getting when it fails is: 

>{"value" : "To screenshot a frame, it must have non-0 area.\n\n(\n\t0   CoreFoundation                      0x0000000188e121d8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x000000018784c55c objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000188e12094 <redacted> + 0\n\t3   Foundation                          0x000000018989f79c <redacted> + 112\n\t4   XCTest                              0x0000000100251ac0 -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192\n\t5   XCTest                              0x000000010025198c -[XCUIScreen screenshotDataForQuality:rect:error:] + 108\n\t6   WebDriverAgentLib                   0x0000000101de2dec -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 740\n\t7   WebDriverAgentLib                   0x0000000101dc4400 +[FBScreenshotCommands handleGetScreenshot:] + 132\n\t8   WebDriverAgentLib                   0x0000000101dd1054 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t9   WebDriverAgentLib                   0x0000000101dc8c80 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t10  RoutingHTTPServer                   0x0000000101e823cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t11  RoutingHTTPServer                   0x0000000101e82b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t12  libdispatch.dylib                   0x0000000187c9d1c0 <redacted> + 16\n\t13  libdispatch.dylib                   0x0000000187cae0c4 <redacted> + 320\n\t14  libdispatch.dylib                   0x0000000187c9d1c0 <redacted> + 16\n\t15  libdispatch.dylib                   0x0000000187ca1d6c _dispatch_main_queue_callback_4CF + 1000\n\t16  CoreFoundation                      0x0000000188dbff2c <redacted> + 12\n\t17  CoreFoundation                      0x0000000188dbdb18 <redacted> + 1660\n\t18  CoreFoundation                      0x0000000188cec048 CFRunLoopRunSpecific + 444\n\t19  Foundation                          0x00000001897fda8c <redacted> + 304\n\t20  WebDriverAgentLib                   0x0000000101dc7c74 -[FBWebServer startServing] + 424\n\t21  WebDriverAgentRunner                0x00000001018bbbe4 -[UITestingUITests testRunner] + 132\n\t22  CoreFoundation                      0x0000000188e18160 <redacted> + 144\n\t23  CoreFoundation                      0x0000000188d0bc3c <redacted> + 284\n\t24  XCTest                              0x000000010023c0a8 __24-[XCTestCase invokeTest]_block_invoke.275 + 48\n\t25  XCTest                              0x000000010023be58 __24-[XCTestCase invokeTest]_block_invoke + 680\n\t26  XCTest                              0x0000000100281780 -[XCUITestContext performInScope:] + 208\n\t27  XCTest                              0x000000010023bba0 -[XCTestCase invokeTest] + 136\n\t28  XCTest                              0x000000010023cc78 __26-[XCTestCase performTest:]_block_invoke.382 + 48\n\t29  XCTest                              0x0000000100286778 +[XCTContext runInContextForTestCase:block:] + 164\n\t30  XCTest                              0x000000010023c674 -[XCTestCase performTest:] + 596\n\t31  XCTest                              0x0000000100238868 __27-[XCTestSuite performTest:]_block_invoke + 288\n\t32  XCTest                              0x0000000100238290 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t33  XCTest                              0x00000001002384a0 -[XCTestSuite performTest:] + 236\n\t34  XCTest                              0x0000000100238868 __27-[XCTestSuite performTest:]_block_invoke + 288\n\t35  XCTest                              0x0000000100238290 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t36  XCTest                              0x00000001002384a0 -[XCTestSuite performTest:] + 236\n\t37  XCTest                              0x0000000100238868 __27-[XCTestSuite performTest:]_block_invoke + 288\n\t38  XCTest                              0x0000000100238290 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t39  XCTest                              0x00000001002384a0 -[XCTestSuite performTest:] + 236\n\t40  XCTest                              0x000000010028ff5c __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44\n\t41  XCTest                              0x000000010024b3e8 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 420\n\t42  XCTest                              0x000000010028fdd8 -[XCTTestRunSession runTestsAndReturnError:] + 292\n\t43  XCTest                              0x0000000100227ed0 -[XCTestDriver runTestsAndReturnError:] + 312\n\t44  XCTest                              0x0000000100285920 _XCTestMain + 620\n\t45  CoreFoundation                      0x0000000188dc0160 <redacted> + 20\n\t46  CoreFoundation                      0x0000000188dbf95c <redacted> + 288\n\t47  CoreFoundation                      0x0000000188dbd7b0 <redacted> + 788\n\t48  CoreFoundation                      0x0000000188cec048 CFRunLoopRunSpecific + 444\n\t49  GraphicsServices                    0x000000018a772198 GSEventRunModal + 180\n\t50  UIKit                               0x000000018ecd82fc <redacted> + 684\n\t51  UIKit                               0x000000018ecd3034 UIApplicationMain + 208\n\t52  WebDriverAgentRunner-Runner         0x00000001000dc430 WebDriverAgentRunner-Runner + 33840\n\t53  libdyld.dylib                       0x0000000187cd05b8 <redacted> + 4\n)",
  "sessionId" : "E7E3B7A2-A404-43D4-AFE2-AFB29C2DA868",
  "status" : 13
}

I've done a little bit more digging and I see now that FBApplication's applicationWithPID method checks to see if the application has already been registered, and if not, it calls `[super applicationWithPID:processID]` and then registers that application. _As an aside, the fb_registerApplicationwithProcessID method accepts an FBApplication and pid_t but just pulls the PID from the FBApplication, so the pid_t passed in is never used. I didn't know if there was a reason for that or not._ But as for the call to super, it returns "Application 'local.pid.52'" as the FBApplication which has a .frame CGSize of 0 by 0, hence the error message stating it needs a non-zero area.

Another thing I see in the console output is that during the call to XCUIApplication's applicationWithPID method, two lines print out saying that the application is not running.
> 2018-02-16 08:48:01.723126 WebDriverAgentRunner-Runner[275:10813] Call super's applicationWithPID...
    t =     3.67s Find the Application "local.pid.52" 0x1700a7980
2018-02-16 08:48:01.887328 WebDriverAgentRunner-Runner[275:10813] Enqueue Failure: Application local.pid.52 is not running /Users/czapfel/Documents/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =     3.79s Find the Application "local.pid.52" 0x1700a7980
2018-02-16 08:48:01.903884 WebDriverAgentRunner-Runner[275:10813] Enqueue Failure: Application local.pid.52 is not running /Users/czapfel/Documents/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
2018-02-16 08:48:01.910390 WebDriverAgentRunner-Runner[275:10813] Supers call got us: local.pid.52 found at (null) with dimensions WxH -> 0.000000 x 0.000000

I am going to continue to look into this, but if anyone has any ideas please let me know.

**Comment by billios1111** [comment] 2018-02-16 14:50
If anyone really needs a janky workaround, you can just hard-code your screen dimensions for now. I am only testing with an iPhone 5s in portrait so the dimensions will always be the same.

**Comment by marekcirkos** [comment] 2018-02-16 16:21
Yep duplicate of https://github.com/facebook/WebDriverAgent/issues/845

**Closed by marekcirkos** 2018-02-16 16:21 UTC
