### ISSUE TITLE
WDA does not listen port 8100 when test executed through xcode

### ISSUE THREAD

**Issue by RameshY703** [facebook/WebDriverAgent#743] opened 2017-10-06 17:58 UTC
WDA does not listen port 8100 when test executed through xcode 9 but it works when I run it through appium 1.7.1 on iPhone 6(v11.0.2).
**Console Output for xcode:**
2017-10-06 23:20:44.439174+0530 WebDriverAgentRunner-Runner[1882:493610] +[CATransaction synchronize] called within transaction
2017-10-06 23:20:44.481824+0530 WebDriverAgentRunner-Runner[1882:493610] Running tests...
2017-10-06 23:20:44.634883+0530 WebDriverAgentRunner-Runner[1882:493610] refreshPreferences: HangTracerEnabled: 0
2017-10-06 23:20:44.636098+0530 WebDriverAgentRunner-Runner[1882:493610] refreshPreferences: HangTracerDuration: 500
2017-10-06 23:20:44.636131+0530 WebDriverAgentRunner-Runner[1882:493610] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
2017-10-06 23:20:46.291598+0530 WebDriverAgentRunner-Runner[1882:493610] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-10-06 23:20:47.527
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-10-06 23:20:47.532
Test Suite 'UITestingUITests' started at 2017-10-06 23:20:47.534
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2017-10-06 23:20:47.539
    t =     0.01s Set Up
2017-10-06 23:20:47.573479+0530 WebDriverAgentRunner-Runner[1882:493610] Built at Oct  6 2017 23:18:39
2017-10-06 23:20:47.624990+0530 WebDriverAgentRunner-Runner[1882:493610] **ServerURLHere->http://192.168.0.103:0<-ServerURLHere**

**Comment by marekcirkos** [comment] 2017-10-20 13:42
Is it already running by any chance? How do you start it?

**Comment by choisuet** [comment] 2017-10-22 12:26
I have encountered with the same issue.
**Environment** list as below:
appium 1.7.1
xcode 9

**I started it by running:**
```
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test
```

**Comment by marekcirkos** [comment] 2017-10-23 10:48
Duplicate of https://github.com/facebook/WebDriverAgent/issues/661

**Closed by marekcirkos** 2017-10-23 10:48 UTC
