### ISSUE TITLE
Tests running time very high due to some blockage #9020

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [facebook/WebDriverAgent#712] opened 2017-09-12 07:28 UTC
The problem

Every time I run a test at the same step / point, Appium seems to be stucked for like 3 minutes.
Before this i'm looking for an element over and over, until it gets displayed and when that label is found the 200 response seems to kill the WDA and it gets stuck for a period(~ 3 minutes) then the test continue to run.

Environment

Appium: 1.6.5
macOS Sierra: 10.12.6
Node.js: 8.1.4
Mobile platform/version under test: iPhone 6 Real Device, iOS version 10.3
xCode: 8.3.3

Link to Appium logs

https://gist.github.com/andreiaionitoaiesv/047c2c2b25b022b7671bcd115561faa6

https://github.com/appium/appium/issues/9020

Any ideas?

**Comment by marekcirkos** [comment] 2017-10-23 10:41
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by marekcirkos** 2017-10-23 10:41 UTC
