### ISSUE TITLE
Cannot get source tree of WebView on iOS 11

### ISSUE THREAD

**Issue by mrhhsg** [facebook/WebDriverAgent#755] opened 2017-10-14 07:58 UTC
<img width="1571" alt="webview" src="https://user-images.githubusercontent.com/1179834/31573977-50e539c6-b0f8-11e7-9303-fbfefa2af5b6.png">

**Comment by marekcirkos** [comment] 2017-10-20 13:35
I have seen this, I suspect this is, because Apple changed making all Views accessible by default to NO. You can try changing that in code.

**Comment by marekcirkos** [comment] 2017-10-23 10:51
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by marekcirkos** 2017-10-23 10:51 UTC
