### ISSUE TITLE
Wrong button being clicked

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#314] opened 2016-10-04 18:31 UTC
We have an Appium user, @joshrlesch, who [reports](https://github.com/appium/appium-xcuitest-driver/issues/209) that the wrong button is being clicked in certain situations. The problem can be tracked to https://github.com/facebook/WebDriverAgent/commit/b2e1c07d1028b696708b64b130292770b72e8052. If that commit is reverted the problem goes away.

I do not know enough about how to both fix this problem and the problem that the commit was itself fixing, unfortunately.

**Comment by marekcirkos** [comment] 2016-10-05 08:54
WDA was crashing sometimes on `isHittable` method, so this diff fixed it. If you have deterministic way of testing it, please create PR with test case on our Integration app and I can have a look at it.

**Comment by imurchie** [comment] 2016-10-06 18:35
I'm still waiting to have a reproducible case. But reverting that commit fixed the problem for the user in question.

**Comment by imurchie** [comment] 2016-10-07 12:42
Anther manifestation of the error: https://github.com/appium/appium/issues/6948

**Comment by dilsreccse** [comment] 2016-10-12 09:40
@marekcirkos : i'm still facing this issue, https://github.com/appium/appium/issues/6941 , when it will be fixed ?

**Comment by imurchie** [comment] 2016-10-20 17:24
This appears to be a manifestation of the LANDSCAPE orientation problem.

**Comment by marekcirkos** [comment] 2016-10-27 08:51
@imurchie Can you check if it happens with new Xcode version?

**Comment by marekcirkos** [comment] 2016-11-02 10:20
Duplicate of https://github.com/facebook/WebDriverAgent/issues/262

**Closed by marekcirkos** 2016-11-02 10:20 UTC
