### ISSUE TITLE
How to handle iphone system popup?

### ISSUE THREAD

**Issue by eguptax** [facebook/WebDriverAgent#861] opened 2018-01-30 02:01 UTC
Hello guys, is there a way to handle iphone system popups during the automation run. There are few popups like "No sim card installed", "wifi networks available" or "verify iphone icloud id" etc. IF any of these popups are available on the iPhone then facebook WebdriverAgent doesn't launch. Is there a way to handle these popups programmatically?

**Comment by amoldhamapurkar** [comment] 2018-01-30 08:43
if you are using appium then use below capabilities.
1. autoAcceptAlerts
2. autoDismissAlerts

**Comment by WaFeIS7** [comment] 2018-02-07 12:34
@amoldhamapurkar it doesn`t work

**Comment by Kitty2014** [comment] 2018-02-08 11:18
also cannot inspector the system popup  @eguptax   if "No sim card installed"  I suggest you Use an invalid SIM card and idevicediagnostics -u YourDeviceUDID  restart
like idevicediagnostics -u 1851e96c01d50f6fbc2032a31a4e903181cdc159 restart

**Comment by Kitty2014** [comment] 2018-02-08 11:20
How to inspector the system popup?  It seem  even inspector OK  but cannot handle with the option which pops up

**Comment by antiarchit** [comment] 2018-02-14 16:33
Duplicate of #859.

**Closed by antiarchit** 2018-02-14 16:33 UTC
