### ISSUE TITLE
WDA cannot start on iOS Simulator

### ISSUE THREAD

**Issue by cbalea** [facebook/WebDriverAgent#536] opened 2017-04-03 08:57 UTC
I have issues with running Appium due to WDA not being able to start on the Simulator. I have tried running this on multiple machines and simulators, but I still get the same error.

This it the opened issue on the Appium project: https://github.com/appium/appium/issues/8149.

I guess that the interesting part for WDA guys starts from this comment in the thread: https://github.com/appium/appium/issues/8149#issuecomment-291074681

**Comment by BenjaminFausett** [comment] 2017-04-03 17:27
I am experiencing the same issue.

Here is the issue I opened on the Appium project: https://github.com/appium/appium/issues/8158

**Comment by mykola-mokhnach** [comment] 2017-04-04 12:29
Seems like updating Xcode to 8.3 does the job: https://github.com/appium/appium/issues/8158#issuecomment-291484085

**Comment by imurchie** [comment] 2017-04-04 14:13
The problem is with the MacOS 10.12.4 update. iOS 10.3 simulators will work fine but eventually 10.2 and lower will fail with WebDriverAgent not being backgroundable and the only recourse being to close the simulator (no amount of fiddling will close the app at this point).

**Comment by marekcirkos** [comment] 2017-04-06 15:29
I guess we can close it?

**Closed** 2017-04-10 10:20 UTC
