### ISSUE TITLE
Unable to do anything when Safari alert open in iOS 9.3

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#263] opened 2016-08-26 20:25 UTC
In 10 everything works. With iOS 9.3 (in both XCode 7.3 and 8 beta 6) when a Safari alert is open and you request the source (also happens with getting an element) an error occurs:

```
Aug 26 13:21:56 isaac mstreamd[69984]: (Warn ) mstreamd: mstreamd shutting down.
Aug 26 13:21:57 isaac XCTRunner[70210]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25215 getting snapshot for element <AXUIElement 0x7fe89370a790> {pid=70220}" UserInfo={NSLocalizedDescription=Error -25215 getting snapshot for element <AXUIElement 0x7fe89370a790> {pid=70220}} <unknown> 0 1
Aug 26 13:22:13 isaac XCTRunner[70210]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25215 getting snapshot for element <AXUIElement 0x7fe89362a400> {pid=70220}" UserInfo={NSLocalizedDescription=Error -25215 getting snapshot for element <AXUIElement 0x7fe89362a400> {pid=70220}} <unknown> 0 1
Aug 26 13:22:29 isaac XCTRunner[70210]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25215 getting snapshot for element <AXUIElement 0x7fe8937091c0> {pid=70220}" UserInfo={NSLocalizedDescription=Error -25215 getting snapshot for element <AXUIElement 0x7fe8937091c0> {pid=70220}} <unknown> 0 1
Aug 26 13:22:44 isaac XCTRunner[70210]: Enqueue Failure: UI Testing Failure - (null) /Users/isaac/code/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
```

And the WebDriverAgent endpoint finally returns

```
Error response status: 13, *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

(
       	0   CoreFoundation                      0x0000000104c7ad85 __exceptionPreprocess + 165
       	1   libobjc.A.dylib                     0x00000001046eedeb objc_exception_throw + 48
       	2   CoreFoundation                      0x0000000104b7723e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
       	3   CoreFoundation                      0x0000000104b895bb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
       	4   WebDriverAgentLib                   0x0000000112115672 +[FBDebugCommands handleGetTreeCommand:] + 706
       	5   WebDriverAgentLib                   0x000000011210fcc3 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
       	6   WebDriverAgentLib                   0x0000000112108384 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
       	7   RoutingHTTPServer                   0x00000001121d5c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
       	8   RoutingHTTPServer                   0x00000001121d64fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
       	9   libdispatch.dylib                   0x00000001075283d7 _dispatch_client_callout + 8
       	10  libdispatch.dylib                   0x0000000107513e2f _dispatch_barrier_sync_f_slow_invoke + 65
       	11  libdispatch.dylib                   0x00000001075283d7 _dispatch_client_callout + 8
       	12  libdispatch.dylib                   0x0000000107512e5d _dispatch_main_queue_callback_4CF + 714
       	13  CoreFoundation                      0x0000000104bd40f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
       	14  CoreFoundation                      0x0000000104b95b99 __CFRunLoopRun + 2073
       	15  CoreFoundation                      0x0000000104b950f8 CFRunLoopRunSpecific + 488
       	16  Foundation                          0x00000001042d8a31 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
       	17  Foundation                          0x000000010436bfe1 -[NSRunLoop(NSRunLoop) run] + 74
       	18  WebDriverAgentLib                   0x00000001121072c6 -[FBWebServer startServing] + 230
       	19  WebDriverAgentRunner                0x0000000110e14aa4 -[UITestingUITests testRunner] + 100
       	20  CoreFoundation                      0x0000000104b635cc __invoking___ + 140
       	21  CoreFoundation                      0x0000000104b6341e -[NSInvocation invoke] + 286
       	22  XCTest                              0x000000010418e210 __24-[XCTestCase invokeTest]_block_invoke_2 + 481
       	23  XCTest                              0x00000001041c69d4 -[XCTestContext performInScope:] + 190
       	24  XCTest                              0x000000010418e01c -[XCTestCase invokeTest] + 255
       	25  XCTest                              0x000000010418e835 -[XCTestCase performTest:] + 457
       	26  XCTest                              0x000000010418b8fd -[XCTestSuite performTest:] + 491
       	27  XCTest                              0x000000010418b8fd -[XCTestSuite performTest:] + 491
       	28  XCTest                              0x000000010418b8fd -[XCTestSuite performTest:] + 491
       	29  XCTest                              0x0000000104177b0c __25-[XCTestDriver _runSuite]_block_invoke + 51
       	30  XCTest                              0x0000000104198fc3 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602
       	31  XCTest                              0x00000001041779a9 -[XCTestDriver _runSuite] + 436
       	32  XCTest                              0x00000001041787a2 -[XCTestDriver _checkForTestManager] + 287
       	33  XCTest                              0x00000001041c7f5c _XCTestMain + 628
       	34  CoreFoundation                      0x0000000104ba02ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
       	35  CoreFoundation                      0x0000000104b95f75 __CFRunLoopDoBlocks + 341
       	36  CoreFoundation                      0x0000000104b956d2 __CFRunLoopRun + 850
       	37  CoreFoundation                      0x0000000104b950f8 CFRunLoopRunSpecific + 488
       	38  GraphicsServices                    0x0000000106d35ad2 GSEventRunModal + 161
       	39  UIKit                               0x0000000105030f09 UIApplicationMain + 171
       	40  XCTRunner                           0x00000001040fd81c XCTRunner + 6172
       	41  libdyld.dylib                       0x000000010755792d start + 1
)
```

**Comment by yaphatak** [comment] 2016-08-28 22:13
@imurchie : Does it fail if we do only accept or dismiss alert?

**Comment by marekcirkos** [comment] 2016-09-05 10:39
Did you try to accept or dismiss this alert using https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBAlertViewCommands.m#L26?

Anyway tree command definitely should not be crashing.

**Comment by marekcirkos** [comment] 2016-09-20 22:09
@imurchie ?

**Comment by marekcirkos** [comment] 2016-09-21 16:37
Duplicate of https://github.com/facebook/WebDriverAgent/issues/273

**Closed by marekcirkos** 2016-09-21 16:37 UTC
Labels: duplicate

**Comment by imurchie** [comment] 2016-09-21 16:57
Sorry, lost track of this one. It still happens. But if it is a sub-problem of #273, hopefully it will get fixed there! Thanks for everything!
