### ISSUE TITLE
Test block Continuing to run tests in the background with task ID 1

### ISSUE THREAD

**Issue by romainlouvet** [facebook/WebDriverAgent#398] opened 2016-12-06 13:12 UTC
When I try to launch my Appium(1.6.2) test with this WDA (from master) with my real device(iPhone 7)

test blocked...

[debug] [WebDriverAgent] Device: Dec 5 10:20:09 iPhoneQA5SBlanc XCTRunner[4277] : Continuing to run tests in the background with task ID 1

**Comment by marekcirkos** [comment] 2016-12-07 00:43
From mine experience this is Xcode issues. WDA is not even being executed at that time.
Rebooting host device and/or iPhone / iPad always fixed this issue.

**Comment by romainlouvet** [comment] 2016-12-07 08:19
Same problem if restart device ... :(

I downgraded with Appium 1.6.1 (using old WDA) -> no problem

**Comment by hepilt** [comment] 2016-12-07 10:17
With Appium 1.6.2 it works with iOS 9, but doesn't work with iOS 10, same message after launching

**Comment by mykola-mokhnach** [comment] 2016-12-07 12:36
Duplicate of https://github.com/facebook/WebDriverAgent/issues/399

**Closed** 2016-12-07 20:43 UTC
