### ISSUE TITLE
The /wda/tap endpoint not working correctly in landscape mode

### ISSUE THREAD

**Issue by rpes** [facebook/WebDriverAgent#798] opened 2017-11-20 17:10 UTC
My env: 
  iPhone 6s with iOS 11.1.2, Xcode 9.1 (9B55)
  WebDriverAgent master code from Nov 20, 2017

Symptoms:

The /wda/tap end point is not performing correctly when the app is in the landscape mode. 
Taps are being applied only to a certain limit of the X-coordinate. It feels like the coordinates 
are internally filtered by the bounding box of the portrait application (375x667).

The issue is not new to the latest iOS 11.1.2. I had the same problem about 2 months ago with an older WDA version and the initial iOS 11 release.

Steps to reproduce:
1. Start the iBooks application
2. Rotate the device to the landscape left mode
3. Select the "My Books" screen (see the screen shot)
4. Tap "Most Recent" at [180,50] -> the tap performs correctly
5. Tap "Authors" - the tap gets applied only if x<375
6. No taps with x>=375 are possible - no way to tap for example "Categories" or "Select"

![ibooks](https://user-images.githubusercontent.com/5822023/33031064-6d5cf2f0-ce1d-11e7-9efd-b684f6684845.png)

The log:

$ export JSON_HEADER='-H "Content-Type: application/json"'

$ curl -X POST $JSONHEADER -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.iBooks\"}}" http://192.168.1.8:8100/session
{
  "value" : {
    "sessionId" : "1D07CE20-34DA-4F86-9B66-FFC96739C9AD",
    "capabilities" : {
      "device" : "iphone",
      "browserName" : "iBooks",
      "sdkVersion" : "11.1.2",
      "CFBundleIdentifier" : "com.apple.iBooks"
    }
  },
  "sessionId" : "1D07CE20-34DA-4F86-9B66-FFC96739C9AD",
  "status" : 0
}

Tap “Most Recent” - SUCCESSFUL

$ curl -X POST $JSONHEADER -d "{\"x\":180,\"y\":50}" http://192.168.1.8:8100/session/1D07CE20-34DA-4F86-9B66-FFC96739C9AD/wda/tap/0
{
  "value" : {

  },
  "sessionId" : "1D07CE20-34DA-4F86-9B66-FFC96739C9AD",
  "status" : 0
}

Tap “Categories” - UNSUCCESSFUL, TAP NOT APPLIED

$ curl -X POST $JSONHEADER -d "{\"x\":490,\"y\":50}" http://192.168.1.8:8100/session/1D07CE20-34DA-4F86-9B66-FFC96739C9AD/wda/tap/0
{
  "value" : {

  },
  "sessionId" : "1D07CE20-34DA-4F86-9B66-FFC96739C9AD",
  "status" : 0
}

**Comment by kycho** [comment] 2017-12-01 00:41
I have same issue. any progress ?

**Comment by clergyman** [comment] 2017-12-01 14:55
Same issue, looks like I am not alone in the universe with this

**Comment by rpes** [comment] 2017-12-05 09:14
There's one more issue. When the keyboard is displayed the taps are mostly misplaced even at coordinates where it works OK in the landscape mode :-(

**Comment by clergyman** [comment] 2017-12-05 10:16
I'd highly appreciate if Appium guys had a look at this stuff, my automation is completely blocked with this, because I work with essentially landscape application. I suppose this is a critical thing

**Comment by marekcirkos** [comment] 2018-02-28 18:16
Duplicate of https://github.com/facebook/WebDriverAgent/issues/856

**Closed** 2018-02-28 18:19 UTC
