### ISSUE TITLE
location Element by XPath fuzzy is intermittently extremely slow（3420s）

### ISSUE THREAD

**Issue by dengwei729** [facebook/WebDriverAgent#345] opened 2016-11-01 11:59 UTC
find a element by xpath take very very long time（**3420s**）.   how can i location the element faster

`

- 2016-11-01 18:32:13.307337 XCTRunner[549:89302] mutableXPath is //XCUIElementTypeStaticText[contains(@name, "没有找到相关城市")]
- t =    65.60s     Get all elements bound by index for: Descendants matching type Any
- t =    65.63s         Snapshot accessibility hierarchy for local.pid.553
- t =    66.57s         Find: Descendants matching type Any
- t =    66.75s     Find the Any
- t =    66.75s         Use cached accessibility hierarchy for local.pid.553
- t =    66.92s         Find: Descendants matching type Any
- t =    67.10s         Find: Element at index 0
- …………………………
- …………………………
- …………………………
- t =  3485.57s     Use cached accessibility hierarchy for com.apple.springboard
- t =  3485.58s     Find: Descendants matching type Sheet
- t =  3485.58s     Find the "没有找到相关城市" StaticText
- t =  3485.58s         Snapshot accessibility hierarchy for local.pid.553
- t =  3486.57s         Find: Descendants matching type Any
- t =  3486.75s         Find: Element at index 1139
- t =  3486.76s     Find the "没有找到相关城市" StaticText
- t =  3486.76s         Use cached accessibility hierarchy for local.pid.553
- t =  3486.94s         Find: Descendants matching type Any
- t =  3487.12s         Find: Element at index 1139
- t =  3487.12s     Find the "没有找到相关城市" StaticText
- t =  3487.12s         Use cached accessibility hierarchy for local.pid.553
- t =  3487.29s         Find: Descendants matching type Any
- t =  3487.47s         Find: Element at index 1139
- 2016-11-01 19:47:06.923840 XCTRunner[549:89302] ----- type ====== 101-----

`

**Comment by marekcirkos** [comment] 2016-11-02 10:10
XPath is slow, but we are working on that https://github.com/facebook/WebDriverAgent/pull/308. I would recommend using regular queries instead https://github.com/facebook/WebDriverAgent/wiki/Queries#searching-for-elements

**Comment by marekcirkos** [comment] 2016-11-02 10:18
Closing duplicate of https://github.com/facebook/WebDriverAgent/issues/306

**Closed by marekcirkos** 2016-11-02 10:18 UTC

**Comment by dengwei729** [comment] 2016-11-03 06:38
OK
