### ISSUE TITLE
WebDriverAgent[IOS10.3][XCTRunner] "Failure fetching attributes for element" when find element in IOS simulator

### ISSUE THREAD

**Issue by coolbirda** [facebook/WebDriverAgent#696] opened 2017-08-26 02:31 UTC
The problem

WebDriverAgent[IOS10.3][XCTRunner]"Failure fetching attributes for element" when find element in IOS simulator

Enqueue Failure: Failure fetching attributes for element 
<XCAccessibilityElement: 0x6080002421f0> 
Device element: Error Domain=XCTDaemonErrorDomain Code=13 
"Error copying attributes -25202" 
UserInfo={NSLocalizedDescription=Error copying attributes -25202} 

Environment

Appium version (or git revision) that exhibits the issue: 1.6.5 & 1.6.6 Beta4 (Sorry I don't )
Last Appium version that did not exhibit the issue (if applicable): 1.6.4
Desktop OS/version used to run Appium: macOS Sierra 10.12.6
Node.js version (unless using Appium.app|exe): 8.4.0
Mobile platform/version under test: IOS 10.3
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: Appium CLI
Details

This issue occurred in Appium 1.6.5 & 1.6.6 Beta4 but it is fine working in 1.6.4

Link to XCTRunner logs

Aug 26 10:15:01 --- last message repeated 2 times ---
Aug 26 10:15:01 dongyideMacBook-Pro XCTRunner[843]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x6080002421f0> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
Aug 26 10:15:01 dongyideMacBook-Pro XCTRunner[843]: Failed to fetch hit point for Other 0x608000774700: {{0.0, 0.0}, {375.0, 667.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
Aug 26 10:15:01 dongyideMacBook-Pro XCTRunner[843]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x6080000507d0> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
Aug 26 10:15:01 dongyideMacBook-Pro XCTRunner[843]: Failed to fetch hit point for Other 0x608000778840: {{0.0, 0.0}, {375.0, 667.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
Aug 26 10:15:01 dongyideMacBook-Pro XCTRunner[843]: Enqueue Failure: Failure fetching attributes for element <XCAccessibilityElement: 0x600000a575b0> Device element: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
Aug 26 10:15:01 dongyideMacBook-Pro XCTRunner[843]: Failed to fetch hit point for Other 0x6000007618c0: {{15.0, 69.0}, {345.0, 305.0}} - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

**Comment by marekcirkos** [comment] 2017-10-23 10:32
Duplicate of https://github.com/facebook/WebDriverAgent/issues/372

**Closed by marekcirkos** 2017-10-23 10:32 UTC
