### ISSUE TITLE
Xcode 9.3 Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by MalcolmCNZ** [facebook/WebDriverAgent#902] opened 2018-04-04 04:44 UTC
Hi There

Webdriver agent was working fine without any Issues, But when i updated to xcode 9.3, i get the"xcode failure" error message, Just wondering if i am the only one who is getting this message after updating to xcode 9.3... All the provisioning certificates are signed.. Please advise.

Thanks
Malcolm

**Comment by AnuKadloor** [comment] 2018-04-04 11:27
Hi @MalcolmCNZ ,
Even I'm facing this issue. I'm using iOS 11.3, xcode 9.3, appium 1.7
The tests were working fine in xcode 9.2
@imurchie Can you help?

Below is the error:-
Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f8ed32950a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2018-04-04 16:30:24.875 xcodebuild[5369:174509] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7f8ed32a7a00 {Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f8ed32950a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
[Xcode] 
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 
[Xcode] Testing failed:
[Xcode] 	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'

**Comment by MalcolmCNZ** [comment] 2018-04-04 22:12
Hi AnuKadloor, 

Please let me know if you find any solution, Yes @imurchie need your help too.. Thank man

**Comment by Biloleg** [comment] 2018-04-05 09:34
The same issue.
I sign WDA lib and WDA runner (as always) and change bundleId for WDA runner.
When I try to install and test WDA from xCode i get:
"Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)"
NOTE: WDA on device is trusted.
When try to run test from Appium i get next error:
Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"
NOTE: WebDriver sign correct (as always)
Please see full xCode log in attached:
[Session-WebDriverAgentRunner-2018-04-05_123134-omIYIE.log](https://github.com/facebook/WebDriverAgent/files/1879383/Session-WebDriverAgentRunner-2018-04-05_123134-omIYIE.log)
[StandardOutputAndStandardError.txt](https://github.com/facebook/WebDriverAgent/files/1879384/StandardOutputAndStandardError.txt)

xCode version 9.3 (9E145)

**Comment by Biloleg** [comment] 2018-04-05 11:03
Reproduce on xCode 9.2 also

**Comment by imurchie** [comment] 2018-04-05 11:38
I cannot open random files. Please someone supply _full_ Appium server logs with xcode logging on as a link to a [gist](https://gist.github.com).

**Comment by imurchie** [comment] 2018-04-05 11:38
I cannot reproduce this with a valid setup.

**Comment by Biloleg** [comment] 2018-04-05 11:44
https://gist.github.com/Biloleg/52b0a28eda51e646e83c40c70223b89f
WDA from appium 1.2.7 installed successful, but from 1.5.0 or directly from facebook/WebDriverAgent git WDA installed but crash when try to run. I check many variants and have same result.

**Comment by Biloleg** [comment] 2018-04-05 11:47
Also xCode log and device crash log:
https://gist.github.com/Biloleg/333cd71ddaed6bf12866f3541296195c
https://gist.github.com/Biloleg/b5ca1cbbcfefff709bd8799677775b72

**Comment by Biloleg** [comment] 2018-04-05 12:01
Downgrade xCode to version 9.2, download WDA again and now it works

**Comment by AnuKadloor** [comment] 2018-04-05 12:09
Hi @imurchie ,
I have provided the logs [here](https://gist.github.com/AnuKadloor/9f8e0ad3a919ba818c18ff911a9b7988)

**Comment by imurchie** [comment] 2018-04-05 14:03
Appium does not use FaceBook's version of WDA, so it is not surprising that it does not work. 

My initial thought is that there is just left over stuff. I would delete `/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-*`, and make sure the app is removed from the device. Then try again from scratch with the build.

I would also make sure you're using Appium 1.8.0-beta (full version coming very soon). 1.7.2 was released _before_ Xcode 9.3 was even released in beta, so it is unlikely to be able to work well.

**Comment by tharrisonbcg** [comment] 2018-04-07 00:39
I was experiencing the same issue after the Xcode 9.3 upgrade. I downgraded Xcode to 9.2, but I was still having trouble getting WDA to launch. I reinstalled Appium Desktop, added the 1.8-beta of appium-server to the Appium Desktop project and that got it working.

**Comment by MalcolmCNZ** [comment] 2018-04-15 21:16
@VenkateshPS ... Did you try to do an hard reset on your IOS device? sometimes it works like a charm...

**Comment by antonkushpil** [comment] 2018-04-17 15:29
The same problem after moving from XCode 9.2 to 9.3
Appium 1.8.0-beta5
Everything is signed properly. Webdriver runner crashes after tests start from XCode and error 65 with appium.
P.S. the second machine with XCode 9.2 works without issues.

**Comment by antonkushpil** [comment] 2018-04-18 10:43
I fixed the issue, 
- Open the WebDriverAgent.xcodeproj
- Select 'Targets' -> 'WebDriverAgentRunner'
- Open 'Build Phases' -> 'Copy frameworks'
- Click '+' -> add 'RoutingHTTPServer'
Thats it!

**Comment by raulosandeep93** [comment] 2018-04-18 13:43
I tried in including **RoutingHTTPServer** please find the logs I'm getting.

ICPL11611:WebDriverAgent sandeepraulo$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=046e4469d6cb14ff57e378599bd4b1d09390472b' test
2018-04-18 19:10:00.607 xcodebuild[4187:83956]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/com.apple.dt.XCTest/IDETestRunSession-9B0D2172-DB3D-4C4B-A07F-A7F7892D7469/WebDriverAgentRunner-8582A6BE-0B2A-4A64-8B8F-E84041B750FC/Session-WebDriverAgentRunner-2018-04-18_191000-fdxlXO.log
2018-04-18 19:10:00.608 xcodebuild[4187:83906] [MT] IDETestOperationsObserverDebug: (BC9C9FD6-88A8-4277-A807-30C9140AD0B4) Beginning test session WebDriverAgentRunner-BC9C9FD6-88A8-4277-A807-30C9140AD0B4 at 2018-04-18 19:10:00.607 with Xcode 9E145 on target <DVTiOSDevice: 0x7fdad82e2b00> {
		deviceSerialNumber:         DMPNWQL6G5VV
		identifier:                 046e4469d6cb14ff57e378599bd4b1d09390472b
		deviceClass:                iPad
		deviceName:                 iPad
		deviceIdentifier:           046e4469d6cb14ff57e378599bd4b1d09390472b
		productVersion:             11.2.6
		buildVersion:               15D100
		deviceSoftwareVersion:      11.2.6 (15D100)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12857221120
		deviceAvailableCapacity:    9922846720
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fdad7c697a0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1,
    2
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (11.2.6 (15D100))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9aed6e76ff4bf27af89562bd422dca29/046e4469d6cb14ff57e378599bd4b1d09390472b/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/sandeepraulo/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa
MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2018-04-18 19:10:15.723139+0530 WebDriverAgentRunner-Runner[403:56415] Running tests...
2018-04-18 19:10:16.319979+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityLabel]
2018-04-18 19:10:16.320095+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityValue]
2018-04-18 19:10:16.320231+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityTraits]
2018-04-18 19:10:16.320325+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl isAccessibilityElement]
2018-04-18 19:10:16.320400+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityIncrement]
2018-04-18 19:10:16.320466+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityDecrement]
2018-04-18 19:10:16.320537+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding +[CAMLightingControl safeCategoryBaseClass]
2018-04-18 19:10:16.321299+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset accessibilityLabel]
2018-04-18 19:10:16.321385+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset accessibilityValue]
2018-04-18 19:10:16.321454+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset accessibilityTraits]
2018-04-18 19:10:16.321521+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset _accessibilityPhotoDescription]
2018-04-18 19:10:16.321590+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding +[PLManagedAsset safeCategoryBaseClass]
2018-04-18 19:10:16.321747+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityLabel]
2018-04-18 19:10:16.321815+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityValue]
2018-04-18 19:10:16.321880+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityTraits]
2018-04-18 19:10:16.321947+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset _accessibilitySavePhotoLabel:]
2018-04-18 19:10:16.322041+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding +[PHAsset safeCategoryBaseClass]
2018-04-18 19:10:16.351685+0530 WebDriverAgentRunner-Runner[403:56415] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2018-04-18 19:10:17.054
Test Suite 'WebDriverAgentRunner.xctest' started at 2018-04-18 19:10:17.055
Test Suite 'UITestingUITests' started at 2018-04-18 19:10:17.056
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2018-04-18 19:10:17.058
    t =     0.00s Set Up
2018-04-18 19:10:17.071844+0530 WebDriverAgentRunner-Runner[403:56415] Built at Apr 18 2018 14:06:33
2018-04-18 19:10:17.110504+0530 WebDriverAgentRunner-Runner[403:56415] ServerURLHere->http://10.11.31.176:0<-ServerURLHere


It is getting stuck at this part and showing either success or any fails.

**Comment by antonkushpil** [comment] 2018-04-18 13:57
@raulosandeep93 yes this looks fine, is WebDriverAgent app launched on your phone/tablet?
If tests don't fail it means it works fine.

**Comment by tsibiski** [comment] 2018-04-18 16:28
This may be the same issue. https://github.com/appium/appium/issues/10554

**Comment by antonkushpil** [comment] 2018-04-18 17:48
@tsibinski you can double check: open xcode and use Product -> Test if test fail then use my solution and try again. Also, you can try to use my fork, this issue seems to be solved there. Don’t forget to run ./Scripts/bootstrap.sh and sign.

**Comment by tsibiski** [comment] 2018-04-18 20:35
Everything works fine when I run Product > Test.

**Comment by antonkushpil** [comment] 2018-04-18 21:00
@tsibiski do you use appium desktop app or console (nmp i appium). Sometimes people check in xcode console version and after run with desktop. I had such situations before in my team.

**Comment by rvankit** [comment] 2018-04-20 14:09
I was facing the same issue as @tsibiski and others from last week and not able to run automation on Mac-OS machines.

I was able to make appium work if I ran it locally through the console after adding RoutingHTTPServer in WebDriverAgentRunner as per https://github.com/facebook/WebDriverAgent/pull/915
But that not work when running through Jenkins.

**Solution:**
I was just trying some hit and trial methods.

I just copied WebDriverAgent folder from a machine which was running older Mac-OS(10.12.6) and Xcode(9.2) to the machine which was running Mac-OS(10.13.4) and Xcode(9.3) and ran appium through the console and then it works with Jenkins as well.

**Location of WebDriverAgent folder:** /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

**Comment by sharecommute** [comment] 2018-04-22 07:45
I had the same issue but found one solution for it. adding one more thing to @antonkushpil  we have to add WebDriveragentlib framework to the webdriveragent project or module. Please refer to the attachment
<img width="873" alt="webdriveragent_project" src="https://user-images.githubusercontent.com/30365273/39092598-52ce43c8-45c6-11e8-864a-dd3ab8b334af.png">


Environment : Appium 1.8.0, Carthage 0.29, ios 11.2.1,

**Comment by gwynjudd** [comment] 2018-04-24 05:44
I also had to add "YYCache.framework" along the same lines

**Comment by disorder1** [comment] 2018-04-26 14:31
Thanks @gwynjudd. 
The same worked for me as @MummanaSubramanya said.
Had to add both "RoutingHTTPServer" and "YYCache.framework" and it compiled.

**Comment by garkinv** [comment] 2018-05-01 20:43
Still facing this issue, adding libs doesn't help to pass Product -> Test.
I got this errors in logs:
`Testing failed:
[Xcode] 	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] dyld: Library not loaded: @rpath/XCTest.framework/XCTest
[Xcode]   Referenced from: /var/containers/Bundle/Application/07D4E0BA-BA4B-4D26-B4AD-1E87C2E7B5C1/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner
[Xcode]   Reason: no suitable image found.  Did find:
[Xcode] 	/private/var/containers/Bundle/Application/07D4E0BA-BA4B-4D26-B4AD-1E87C2E7B5C1/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/07D4E0BA-BA4B-4D26-B4AD-1E87C2E7B5C1/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
[Xcode] 	/private/var/containers/Bundle/Application/07D4E0BA-BA4B-4D26-B4AD-1E87C2E7B5C1/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/07D4E0BA-BA4B-4D26-B4AD-1E87C2E7B5C1/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'`

**Comment by garkinv** [comment] 2018-05-03 14:04
**Solved**
I solved my issue after - I untrusted all manually trusted developer and root certificates in keychain.
All certificates should be - Use system defaults.

**Closed** 2018-05-10 08:06 UTC

**Comment by 13409795771** [comment] 2019-06-30 07:07
> @mykola-mokhnach I tried in including **RoutingHTTPServer** please find the logs I'm getting.
> 
> ICPL11611:WebDriverAgent sandeepraulo$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=046e4469d6cb14ff57e378599bd4b1d09390472b' test
> 2018-04-18 19:10:00.607 xcodebuild[4187:83956] IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/com.apple.dt.XCTest/IDETestRunSession-9B0D2172-DB3D-4C4B-A07F-A7F7892D7469/WebDriverAgentRunner-8582A6BE-0B2A-4A64-8B8F-E84041B750FC/Session-WebDriverAgentRunner-2018-04-18_191000-fdxlXO.log
> 2018-04-18 19:10:00.608 xcodebuild[4187:83906] [MT] IDETestOperationsObserverDebug: (BC9C9FD6-88A8-4277-A807-30C9140AD0B4) Beginning test session WebDriverAgentRunner-BC9C9FD6-88A8-4277-A807-30C9140AD0B4 at 2018-04-18 19:10:00.607 with Xcode 9E145 on target <DVTiOSDevice: 0x7fdad82e2b00> {
> deviceSerialNumber: DMPNWQL6G5VV
> identifier: 046e4469d6cb14ff57e378599bd4b1d09390472b
> deviceClass: iPad
> deviceName: iPad
> deviceIdentifier: 046e4469d6cb14ff57e378599bd4b1d09390472b
> productVersion: 11.2.6
> buildVersion: 15D100
> deviceSoftwareVersion: 11.2.6 (15D100)
> deviceArchitecture: arm64
> deviceTotalCapacity: 12857221120
> deviceAvailableCapacity: 9922846720
> deviceIsTransient: NO
> ignored: NO
> deviceIsBusy: NO
> deviceIsActivated: YES
> deviceActivationState: Activated
> isPasscodeLocked: NO
> deviceType: <DVTDeviceType:0x7fdad7c697a0 Xcode.DeviceType.iPhone>
> supportedDeviceFamilies: (
> 1,
> 2
> )
> applications: (null)
> provisioningProfiles: (null)
> hasInternalSupport: NO
> isSupportedOS: YES
> developerDiskMountError: (null)
> (null)
> bootArgs: 
> connected: yes
> isWirelessEnabled: no
> connectionType: direct
> } (11.2.6 (15D100))
> === BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
> 
> Check dependencies
> 
> === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===
> 
> Check dependencies
> 
> MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> state->old_bundle: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9aed6e76ff4bf27af89562bd422dca29/046e4469d6cb14ff57e378599bd4b1d09390472b/WebDriverAgentRunner-Runner.app
> state->new_bundle: /Users/sandeepraulo/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> state->dst_bundle: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> dst_ipa: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa
> MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.4c1ohN/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> 2018-04-18 19:10:15.723139+0530 WebDriverAgentRunner-Runner[403:56415] Running tests...
> 2018-04-18 19:10:16.319979+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityLabel]
> 2018-04-18 19:10:16.320095+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityValue]
> 2018-04-18 19:10:16.320231+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityTraits]
> 2018-04-18 19:10:16.320325+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl isAccessibilityElement]
> 2018-04-18 19:10:16.320400+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityIncrement]
> 2018-04-18 19:10:16.320466+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityDecrement]
> 2018-04-18 19:10:16.320537+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding +[CAMLightingControl safeCategoryBaseClass]
> 2018-04-18 19:10:16.321299+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset accessibilityLabel]
> 2018-04-18 19:10:16.321385+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset accessibilityValue]
> 2018-04-18 19:10:16.321454+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset accessibilityTraits]
> 2018-04-18 19:10:16.321521+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PLManagedAsset _accessibilityPhotoDescription]
> 2018-04-18 19:10:16.321590+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding +[PLManagedAsset safeCategoryBaseClass]
> 2018-04-18 19:10:16.321747+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityLabel]
> 2018-04-18 19:10:16.321815+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityValue]
> 2018-04-18 19:10:16.321880+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset accessibilityTraits]
> 2018-04-18 19:10:16.321947+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding -[PHAsset _accessibilitySavePhotoLabel:]
> 2018-04-18 19:10:16.322041+0530 WebDriverAgentRunner-Runner[403:56415] [AXValidations] UIAccessibility Error adding +[PHAsset safeCategoryBaseClass]
> 2018-04-18 19:10:16.351685+0530 WebDriverAgentRunner-Runner[403:56415] Continuing to run tests in the background with task ID 1
> Test Suite 'All tests' started at 2018-04-18 19:10:17.054
> Test Suite 'WebDriverAgentRunner.xctest' started at 2018-04-18 19:10:17.055
> Test Suite 'UITestingUITests' started at 2018-04-18 19:10:17.056
> Test Case '-[UITestingUITests testRunner]' started.
> t = 0.00s Start Test at 2018-04-18 19:10:17.058
> t = 0.00s Set Up
> 2018-04-18 19:10:17.071844+0530 WebDriverAgentRunner-Runner[403:56415] Built at Apr 18 2018 14:06:33
> 2018-04-18 19:10:17.110504+0530 WebDriverAgentRunner-Runner[403:56415] ServerURLHere->http://10.11.31.176:0<-ServerURLHere
> 
> It is getting stuck at this part and showing either success or any fails.

yes, I have the same problem, can you tell me you solved ?
