### ISSUE TITLE
Unable to launch app some applications on device

### ISSUE THREAD

**Issue by sapieneptus** [facebook/WebDriverAgent#97] opened 2016-01-14 00:24 UTC
Xcode 7.3 beta, iPhone6, iOS 9.2
(Tried to do this on Xcode 7.2 stable, but ran into [this issue](https://github.com/facebook/WebDriverAgent/issues/96)).

Forgive me if I'm missing something fundamental, but here are the steps to repro:

Following the README, I start the server by running the UITestingUITests test.
I see the blue screen on the device and logs indicating that the server is ready. 

Then I POST the following:
```json
{
    "desiredCapabilities" : {
        "bundleId" : "my.bundle.id",
        "app" : "/Users/me/path/to/my/bundle.app"
    }
}
```

The app starts launching, but never gets past the launch screen. We get an error originating from `[app launch]` in `+ [FBSessionCommands routes]` for `POST /session`:

```
<unknown>:0: error: -[UITestingUITests testRunner] : UI Testing Failure - Failure 
attempting to launch <XCUIApplicationImpl: 0x155d9b0e0 my.bundle.id at 
/Users/me/path/to/my/bundle.app>: Error Domain=XCTestIDEInterfaceErrorDomain Code=11 "Expired token: no operation still exists for this token." UserInfo={NSLocalizedDescription=Expired token: no operation still exists for this token.}
```

Reading through the XCUITest logs, it looks like it is trying to launch the app, but gets stuck on something. The following logs repeat dozens of times before the failure:
```
15:34:26.021 Xcode[23698:192220] Test process requested launch process status with token 140567250394480
15:34:26.021 Xcode[23698:192220] Got status 0 from operation for token 140567250394480
15:34:26.124 XCTStubApps[994:291909]    Got status 0
15:34:26.124 XCTStubApps[994:291659]    Throttling status checking for 0.197316s...
15:34:26.323 XCTStubApps[994:291659]    Checking status...
```

**Comment by marekcirkos** [comment] 2016-01-14 15:17
I have seen this once. Try running app with Xcode, and then use that build. I think it has something todo with way app is build, configuration, prov profile, etc. I haven't figured it out yet.

**Comment by sapieneptus** [comment] 2016-01-14 15:40
Hi @marekcirkos, thanks for your response!

I'm actually trying to test a build on device, so I'm using the `.ipa` that's exported from xcode. If I build to device directly from xcode, to what would I point the `appBundle` parameter? 

It doesn't jump out as a codesigning issue to me, since an app installed via XCUITestDriver can still be used manually _after_ the test has failed. If it were strictly a codesigning problem, we'd likely see it crashing immediately as launch starts.

**Comment by marekcirkos** [comment] 2016-01-15 00:29
If you check build logs you will see application `.app` being created in DerivedData folder. Just grab it.

According to prov profile I was thinking more of app being signed with developer profile vs ad-hoc or release, but haven't confirmed it yet. It could be also some build setting. I found `.app` that refuses to be installed so I will investigate it later. Till then try using Xcode build signed with developer profile.

**Comment by sapieneptus** [comment] 2016-01-15 01:35
@marekcirkos You are correct - using the build from DerivedData seems to work. If I can find the root cause I'll make a PR :) 

I might leave the issue open for now (or make a new one around finding a fix), but it's up to you.  

Thank you for your help!

**Comment by mmmulani** [comment] 2016-02-16 12:10
@sapieneptus I'm going to close this for now, if you determine the root cause feel free to add it to the README :)

**Closed by mmmulani** 2016-02-16 12:10 UTC

**Comment by rob-nash** [comment] 2018-06-20 07:05
@marekcirkos @sapieneptus did you figure this out, in the end? Found you guys via google search for this error. I'm getting the same issue for a different project, built on travis continuous integration.
