### ISSUE TITLE
127.0.0.1:8100/inspector page blank

### ISSUE THREAD

**Issue by lengyao88** [facebook/WebDriverAgent#633] opened 2017-07-03 05:33 UTC
inspector page blank

**Comment by tcguo** [comment] 2017-07-03 08:49
me too

**Comment by tcguo** [comment] 2017-07-03 08:51
me too ,


{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "10.3.1"
    },
    "ios" : {
      "simulatorVersion" : "10.3.1",
      "ip" : "10.129.163.119"
    },
    "build" : {
      "time" : "Jul  3 2017 10:47:01"
    }
  },
  "sessionId" : "E1092EA4-7DB3-40AB-B71B-7E113F1E30BB",
  "status" : 0
}

**Comment by marekcirkos** [comment] 2017-07-10 10:11
Did you run bootstrap script?

**Comment by crazyk2** [comment] 2017-07-11 12:47
I've got the same problem. 
Downloaded latest version from github, 
ran `scripts/bootstrap.sh`,
ran `xcodebuild build-for-testing test-without-building -project /Users/user/driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=444B894A-22EF-4277-91FF-384C0EEE3A93 IPHONEOS_DEPLOYMENT_TARGET=10.3`
opened `localhost:8100/inspector`
and catched the same error

**Comment by marekcirkos** [comment] 2017-07-11 13:35
What is your node version?

**Comment by marekcirkos** [comment] 2017-07-11 13:36
I guess this is duplicate of https://github.com/facebook/WebDriverAgent/issues/632

**Comment by crazyk2** [comment] 2017-07-11 13:42
node -v
v7.5.0

**Comment by jmei08** [comment] 2017-07-12 03:04
the same problem. I have fetched WDA independently and run bootstrap script which completed without any errors. The node version is 8.1.3 and npm version is 5.0.3.  
It has bothered me for several days...

**Comment by psb01** [comment] 2017-07-12 21:00
Same problem.

**Comment by wendywenwen** [comment] 2017-07-13 07:00
the same problem. bootstrap script completed without errors.  @marekcirkos

**Comment by marekcirkos** [comment] 2017-07-14 08:52
I suspect this is node version issue, but this is blind guess. I'll have a look after we resolve Xcode 11

**Comment by Chenneyfang** [comment] 2017-07-14 13:36
i had met the same problem

**Comment by FrankThonig** [comment] 2017-07-16 09:46
same problem

**Comment by lujun-wuhan** [comment] 2017-07-17 06:31
me too

**Comment by pluie-cloud** [comment] 2017-07-21 01:45
my problem is：
when i input localhost:8100/inspector debug code find:
return [[self inspectorResourcesBundle] pathForResource:@"index" ofType:@"html"]；
return nil;
ths

**Comment by marekcirkos** [comment] 2017-07-24 11:00
Should be fixed with https://github.com/facebook/WebDriverAgent/commit/2ed25a24ed0286b1282f4ca2afc95ceec8d89560 can you confirm?

**Closed** 2017-08-05 21:24 UTC
