### ISSUE TITLE
iOS 11 is too slow

### ISSUE THREAD

**Issue by colinator** [facebook/WebDriverAgent#754] opened 2017-10-12 21:31 UTC
Running against iOS 11 seems to be 10x slower than iOS 10.3.

First time user; following the directions here:
https://github.com/facebook/WebDriverAgent and here:
https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent; running the webdriveragent from xcode in simulator.

I'm following the very basic directions, and doing this:
```
curl -X POST $JSON_HEADER -d "{\"using\":\"link text\",\"value\":\"label=Sign Up\"}" 
 $DEVICE_URL/session/$SESSION_ID/elements
curl -X POST $JSON_HEADER -d "" $DEVICE_URL/session/$SESSION_ID/element/<ELEMENT>/click
```
The /click method takes about 1 second on iOS 10.3, and about **10 seconds or more** against iOS 11.

Is there anything I'm doing wrong? I'm just following the basic directions at https://github.com/facebook/WebDriverAgent/wiki/Queries.

**Comment by marekcirkos** [comment] 2017-10-20 13:36
We have some loops to make sure WDA is more stable, I assume something changed on iOS 11. That makes them super bad. We will need to investigate that.

**Comment by marekcirkos** [comment] 2017-10-23 10:51
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by marekcirkos** 2017-10-23 10:51 UTC
