### ISSUE TITLE
On launching App store fetching source, inspector stops working

### ISSUE THREAD

**Issue by vinodvpatil** [facebook/WebDriverAgent#710] opened 2017-09-08 16:36 UTC
Launch the App store and open the source or the inspector endpoint. None of the end points respond, logs below,

 t =    36.87s         Find the Application "local.pid.53" 0x1700afd20
    t =    36.88s             Snapshot accessibility hierarchy for local.pid.53
    t =    36.96s             Wait for app to idle
    t =    37.38s         Synthesize event
    t =    37.69s             Find the Application "local.pid.53" 0x1700afd20
    t =    37.69s                 Snapshot accessibility hierarchy for local.pid.53
    t =    37.88s         Wait for app to idle
    t =    38.32s     Find the Application "local.pid.201" 0x1700afde0
    t =    38.32s         Snapshot accessibility hierarchy for local.pid.201
2017-09-08 22:00:36.895316+0530 XCTRunner[239:8251] Enqueue Failure: Failure getting snapshot Error Domain=XCTDaemonErrorDomain Code=9 "Error -25204 getting snapshot for element <AXUIElement 0x10fd4dc90> {pid=201}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element <AXUIElement 0x10fd4dc90> {pid=201}} <unknown> 0 1
    t =    54.34s         Find the Application "local.pid.201" 0x1700afde0 (retry 1)
    t =    54.34s             Snapshot accessibility hierarchy for local.pid.201

This seems to be happening  on home page of App Store

**Comment by marekcirkos** [comment] 2017-10-23 10:40
Duplicate of https://github.com/facebook/WebDriverAgent/issues/372.
As workaround you could try adding a nasty sleep after app switch.

**Closed by marekcirkos** 2017-10-23 10:40 UTC
