### ISSUE TITLE
Appium 1.7.1 Automation is too slow

### ISSUE THREAD

**Issue by stephenws** [facebook/WebDriverAgent#739] opened 2017-10-03 15:56 UTC
I have updated Appium 1.7.1 from 1.6.4 and I observed that it is running too slow.
for me it took more than 5 minutes to run Enter Username, Enter Password and click on Login button
It was working fine with proper speed in appium 1.6.4

Appium version (or git revision) that exhibits the issue: 1.7.1
Last Appium version that did not exhibit the issue (if applicable): 1.6.4
Desktop OS/version used to run Appium: MacOS Sierra 10.12.6
Node.js version (unless using Appium.app|exe): v6.11.0
Mobile platform/version under test: iOS 10.0.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

https://gist.github.com/stephenws/a8ed795460d329af6fb95fc46c3def6e

**Comment by welnanick** [comment] 2017-10-03 18:20
I am also noticing a huge drop off of speed using appium to test iOS when I upgraded to version 1.7.1. I would say that its almost 3x-4x slower now.

**Comment by ptsiakos77** [comment] 2017-10-05 16:56
Do you use XPath selectors? Because from appium 1.6.5 and later the way that the Xpath selectors visibility is handled changed introducing very big delays in Xpath

**Comment by stephenws** [comment] 2017-10-05 17:21
Yeah. For xpath selector automation stuck to find xpath,even for id it tooks time.

**Comment by welnanick** [comment] 2017-10-05 17:47
@ptsiakos77 I only use xpath on iOS when I absolutely have to. Most of my elements are found using the accessibility id or a predicate string. Furthermore I was using 1.7.0 Beta for appium and then upgraded to 1.7.1, and that is when I noticed the tests get slower.

**Comment by ptsiakos77** [comment] 2017-10-06 13:06
I had such kind of problems in the past but it was due to a bug MacOS Sierra wed driver polling mechanism to find elements. I had to append the computer hostname to etc/hosts file as a workaround like below:

127.0.0.1	localhost QAs-iMac.local
255.255.255.255	broadcasthost 
::1             localhost QAs-iMac.local

But I am not sure that this is the case here.

**Comment by welnanick** [comment] 2017-10-06 16:43
It almost seems like there is an artificial pause in between commands now.

**Comment by testwa** [comment] 2017-10-07 05:49
I found the issue also,the "/source" command is very slow,and if i request the command too ofter,the wda will crash.

**Comment by ledinhphuong** [comment] 2017-10-07 07:31
It takes to long to response for `/source` and `/elements` endpoints.

**Comment by stephenws** [comment] 2017-10-09 06:52
Anyone got any solution on this?

**Comment by dorsegal** [comment] 2017-10-09 07:13
We tried to checkout to an earlier commit but without luck.
Does anyone if we need to do anything else like building it manually or something?

**Comment by Lexx918** [comment] 2017-10-10 15:26
It's time to add [NSPredicate](https://academy.realm.io/posts/nspredicate-cheatsheet/) as the main type of locators!

**Comment by mykola-mokhnach** [comment] 2017-10-10 15:40
https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

**Comment by welnanick** [comment] 2017-10-10 16:16
@mykola-mokhnach Thanks for the link, I'll see if that speeds up my tests any!

**Comment by welnanick** [comment] 2017-10-11 22:53
So even after optimizing my lookups using the link that was provided, my iOS test still run slower than they used to. At the moment they take about 45 minutes to run compared to Android, which takes 20 minutes. These are the same tests between the platforms, and prior to Appium 1.7.1 they both ran in about the same amount of time.

**Comment by stephenws** [comment] 2017-10-12 06:00
Anyone knows about appium 1.7.0 feedback on Performance Speed issue. Because 1.7.1 is too slow so thinking about to downgrade appium to 1.7.0

**Comment by mykola-mokhnach** [comment] 2017-10-12 06:13
Try 1.7.2@beta. We added some improvements there and also merged the recent WDA changes

**Comment by welnanick** [comment] 2017-10-12 17:53
Switching to 1.7.2@beta helped, shaved about 15 minutes off the running time for iOS. Down to 30 minutes now on iOS compared to Android's 20 minutes, so it's still not quite where it used to be, but definitely a lot better. Thanks for all the hard work!

**Comment by marekcirkos** [comment] 2017-10-23 10:48
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by marekcirkos** 2017-10-23 10:48 UTC

**Comment by hardik-plume** [comment] 2017-12-22 02:33
@welnanick any other issues on beta 😉 ? i cannot deal with such slow performance. almost makes the tool useless for me. Thinking whether should go back to 1.6.4 or beta.

**Comment by raymondlapak** [comment] 2018-01-30 08:37
@welnanick just out of curiosity, how many tests are there for the 30 minutes duration? I am just switching to Appium from XCUITest; it is comparably much slower than running the XCUITest directly on XCode for me :(

**Comment by welnanick** [comment] 2018-02-06 19:45
@hardik-plume @raymondlapak Unfortunately I do not work for the company anymore that I was writing Appium tests for. Since I haven't seen the code base or used it in almost 2 months now, I can't answer your questions, sorry.

**Comment by dzaiats** [comment] 2018-05-15 11:25
Hi guys! I found the solution. Use the capability useJSONSource=true. It makes getting of source 2x or 3x faster.

**Comment by dhinaraj** [comment] 2018-10-29 10:46
I'm also facing similar issue. I tried using useJSONSource=true , but no improvement is seen. Any solution for this please?

**Comment by mkikot-sigma** [comment] 2018-10-29 17:03
This is pain. Clicking the "Allow" button in bare safari takes up to two minutes, where finding by accessibility ID and clicking the element take both more than 40 seconds each.

**Comment by Jaspreet23** [comment] 2018-10-30 23:56
I am facing the same issue with iOS app automation with Appium. It takes more than a 1m few seconds for a simple step such as a button click. And I am not using xpaths. I am either using @iOSFindBy(id="someid") or  @iOSXCUITFindBy(iOSNsPredicate = "")
If any element is not present for which I check in 'if condition' it takes 20-30 tries before moving to next line which is making it extremely slow.
Any help please!!

**Comment by aryalakshmi** [comment] 2018-11-26 09:45
Hi All,
I am also facing the same issue. Rendering of xpaths is to slow in iOS. I am using 1.8.2-beta version appium.
xcode version is 10.1
MAC is a High Sierra

**Comment by prakashpqa** [comment] 2018-12-04 13:57
I am too facing the issue of finding and executing commands to be too slow. I am automating an app in which a drop down has 400 listing. To scroll and select the option it's taking more than 1 hour rendering the tool useless to me. I am using appium 1.9.1 (CLI) and appium 1.8.2 (Desktop)... Has anybody found a solution for this?

**Comment by sudeeppaudyal** [comment] 2018-12-04 21:33
Any Solution guys to speed up the test?

**Comment by vivekkulshresth** [comment] 2018-12-22 20:43
When we enter some text in a text box it takes a pause of 3 seconds prior to entering the text and 3 seconds after that. Any solution ?

**Comment by CrispJam** [comment] 2019-02-06 12:53
I'm getting particularly slow results when using the find_elements method. I tried setting implicit wait to 0 but it doesn't seem to do anything. Any ideas on what I could do about this?

**Comment by SergiiNik** [comment] 2019-06-15 03:38
I tried everything but only this helped 
Just add capability: waitForQuiescence = false
