### ISSUE TITLE
iOS10.0.2 real device can't use it

### ISSUE THREAD

**Issue by lvduoqiang** [facebook/WebDriverAgent#330] opened 2016-10-17 02:41 UTC
i make some tests for devices。
1、iOS9+iphone6s 
localhost:8100  ok
ip:8100  ok

2、iOS10+iphone6s
localhost:8100   ok
ip:8100   NO

it can not work at iOS10，when use ip 。
proxy.js:58:18 [master] pid:31993 xctest client proxy error with: Error: connect ETIMEDOUT 172.20.28.21:8100

**Comment by marekcirkos** [comment] 2016-10-17 09:48
If you can connect via localhost it means WDA booted properly. This might be your wifi configuration issue, blocking some connections or it is duplicate of [this issue](https://github.com/facebook/WebDriverAgent/issues/288)

**Closed by marekcirkos** 2016-10-17 09:48 UTC

**Comment by lvduoqiang** [comment] 2016-10-20 01:51
why iOS9 can use ip。。。。i don't think my wifi has problem。。。
