### ISSUE TITLE
Failed to fetch hit point for ***

### ISSUE THREAD

**Issue by lingtingSir** [facebook/WebDriverAgent#723] opened 2017-09-18 09:26 UTC
XCElementSnapshot (FBHitPoint)   When the page elements in the outside of the screen, call the [self fb_hitPoint] method will appear memory usage surge problem, performance is a serious problem, the Logs:Failed to fetch hit point for * *, is there a better solution?

**Comment by lingtingSir** [comment] 2017-09-20 06:33
XCElementSnapshot (FBIsVisible)  fb_isVisible: Internal call self.visibleFrame .There are serious performance problems. Is there any way to solve it?

**Comment by marekcirkos** [comment] 2017-10-23 10:42
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639

**Closed by marekcirkos** 2017-10-23 10:42 UTC
