### ISSUE TITLE
/inspector endpoint not loading properly

### ISSUE THREAD

**Issue by goldeelox** [facebook/WebDriverAgent#632] opened 2017-06-29 16:08 UTC
I get the following JS error when trying to load the /inspector endpoint on an active WDA session. As a result, the inspector page remains blank.

```
Uncaught TypeError: Super expression must either be null or a function, not undefined
    at _inherits (inspector.js:23267)
    at inspector.js:23278
    at Object.hasOwn (inspector.js:23352)
    at __webpack_require__ (inspector.js:20)
    at Object.defineProperty.value (inspector.js:23093)
    at __webpack_require__ (inspector.js:20)
    at Object.<anonymous> (inspector.js:91)
    at __webpack_require__ (inspector.js:20)
    at Object.<anonymous> (inspector.js:47)
    at __webpack_require__ (inspector.js:20)
```

**Comment by zhuguoqiang** [comment] 2017-06-30 06:59
I get same error:
TypeError: Super expression must either be null or a function, not undefined
and other endpoint localhost:8100/status  and  localhost:8100/source  working fine

**Comment by marekcirkos** [comment] 2017-07-10 10:12
Did you run bootstrap script?

**Comment by goldeelox** [comment] 2017-07-10 23:49
Yes. The bootstrap completes without any errors.

**Comment by marekcirkos** [comment] 2017-07-11 13:36
Duplicate of https://github.com/facebook/WebDriverAgent/issues/632

**Closed by marekcirkos** 2017-07-11 13:36 UTC
