### ISSUE TITLE
Cannot get screentshot in inspector.

### ISSUE THREAD

**Issue by liyuankunbix** [facebook/WebDriverAgent#834] opened 2018-01-06 14:14 UTC
As the title described, i cannot extract screenshot in inspector.
![2018-01-06 9 33 40](https://user-images.githubusercontent.com/17062356/34640462-f11f925c-f32d-11e7-9447-a82883b9d091.png)
However, **the Home Button works !**

Here is my environment information:
macOS 10.12.6 + **XCode 9.2**
iPhone 5S + **iOS 9.3.5**

Here is a brief report of this error

> 2018-01-06 21:58:57.622 WebDriverAgentRunner-Runner[281:20953] Enqueue Failure: Application local.pid.54 is not running /Users/liyuankun/WebDriverAgent1/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =  3300.28s Find the Application "local.pid.54" 0x12d905390
2018-01-06 21:58:57.645 WebDriverAgentRunner-Runner[281:20953] Enqueue Failure: Application local.pid.54 is not running /Users/liyuankun/WebDriverAgent1/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =  3300.49s Find the Application "local.pid.54" 0x12d904670
2018-01-06 21:58:57.864 WebDriverAgentRunner-Runner[281:20953] Enqueue Failure: Application local.pid.54 is not running /Users/liyuankun/WebDriverAgent1/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =  3300.51s Find the Application "local.pid.54" 0x12d904670
2018-01-06 21:58:57.884 WebDriverAgentRunner-Runner[281:20953] Enqueue Failure: Application local.pid.54 is not running /Users/liyuankun/WebDriverAgent1/WebDriverAgentRunner/UITestingUITests.m 37 1
2018-01-06 21:58:57.893 WebDriverAgentRunner-Runner[281:20953] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230

If you need anything necessary , plz do reply me or contact me. I will upload it immediately.

**Comment by Mikebanana** [comment] 2018-01-07 14:42
I have the same problem. 
WebDriverAgentRunner-Runner[347:40062] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13201/Sources/UITesting/XCUIScreen.m:230

**Comment by KiritoStudio** [comment] 2018-01-09 14:52
Same issue here.
macOS 10.13.2 + XCode 9.2
iPhone 6S + iOS 9.3.2

**Comment by KiritoStudio** [comment] 2018-01-11 14:33
After debugging with XCode, I found the app.frame could not be calculated. What can I do?

`- (NSData *)fb_screenshotWithError:(NSError*__autoreleasing*)error
{
  Class xcScreenClass = objc_lookUpClass("XCUIScreen");
  if (nil == xcScreenClass) {
    NSData *result = [[XCAXClient_iOS sharedClient] screenshotData];
    if (nil == result) {
      if (error) {
        *error = [[FBErrorBuilder.builder withDescription:@"Cannot take a screenshot of the current screen state"] build];
      }
      return nil;
    }
    return result;
  }

  XCUIApplication *app = FBApplication.fb_activeApplication;
  CGSize screenSize = FBAdjustDimensionsForApplication(app.frame.size, app.interfaceOrientation);
  // https://developer.apple.com/documentation/xctest/xctimagequality?language=objc
  // Select lower quality, since XCTest crashes randomly if the maximum quality (zero value) is selected
  // and the resulting screenshot does not fit the memory buffer preallocated for it by the operating system
  NSUInteger quality = 1;
  CGRect screenRect = CGRectMake(0, 0, screenSize.width, screenSize.height);

  XCUIScreen *mainScreen = (XCUIScreen *)[xcScreenClass mainScreen];
  NSData *result = [mainScreen screenshotDataForQuality:quality rect:screenRect error:error];
  if (nil == result) {
    return nil;
  }

  // The resulting data is a JPEG image, so we need to convert it to PNG representation
  UIImage *image = [UIImage imageWithData:result];
  return (NSData *)UIImagePNGRepresentation(image);
}`

**Comment by KiritoStudio** [comment] 2018-01-12 15:41
I found the workaround.
According to #639 and #778 and #752, it seems XCode 9.X does not work with iOS 9.X and iOS 10.X devices and support for Xcode 9 does not fully supported yet. So the solution if you want the WebDriverAgentRunner work is use Xcode 8.X and get the codes before project upgrade to 9.X. After I checkout the with d6525b862bc91b670a8631d024bc7d018bc8f574 and the screenshot works fine.
![image](https://user-images.githubusercontent.com/553215/34882436-881e36dc-f7f1-11e7-8678-ce9c9c9cdedc.png)

Cheers!

**Comment by teeceepee** [comment] 2018-01-14 12:34
Almost the same issue. Sometimes it works well, but most of the time it's broken.

macOS 10.12.6
Xcode 9.2
iPhone SE
iOS 10.2.1

**Comment by marekcirkos** [comment] 2018-02-28 17:59
Duplicate of https://github.com/facebook/WebDriverAgent/issues/845

**Closed by marekcirkos** 2018-02-28 17:59 UTC
